### PR TITLE
adjusted footer-button padding to center icons

### PR DESCRIPTION
**Pull request by eyoa**
The icon image itself isn't square so it wasn't vertically centered.
I adjusted the top padding value in the scss file for the footer button to be 2px.

### CODE REVIEW

**Review by park-junha — CHANGES_REQUESTED** [review]
This is great and mostly looks good, thank you for contributing!

Can you run `yarn bump patch` and commit the resulting files to this pull request? This will bump the version number of the app up, which is required for the Chrome Web Store and Firefox Add-Ons.

I will merge your changes afterwards. Thank you!

**Review by park-junha — APPROVED** [review]
Looks good! Will merge shortly.

**Comment by eyoa** [comment]
Cool! I've bumped up the version. 
Thanks!

**Comment by park-junha** [comment]
Merged to `master` @ https://github.com/park-junha/where-to/commit/f4ed89583283bd8d2a296586deab1818baac0aae - thank you for contributing @eyoa!

**Pull request closed without merging**
